#!/usr/bin/env python3
"""Regenerates Lookout's country data from a DB-IP edition and a flag-icons release.

    tools/make-geo.py <YYYY-MM> <flag-icons tag>      e.g. tools/make-geo.py 2026-10 v7.5.0

Needs the network, git, rsvg-convert and ImageMagick's magick. Writes assets/geo/ipv4-countries.bin (a u32 count, the
range starts as u32 little-endian, then one country index byte per range), assets/geo/flags.png (one cell per country,
in index order), src/geo/private/country_table.cpp and the two notices in assets/licences/.
"""

import argparse
import csv
import gzip
import io
import ipaddress
import json
import pathlib
import struct
import subprocess
import sys
import tempfile
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
DBIP_URL = "https://download.db-ip.com/free/dbip-country-lite-{month}.csv.gz"
FLAGS_REPO = "https://github.com/lipis/flag-icons"
UNKNOWN_CODE = "ZZ"
NO_COUNTRY = 255
CELL_WIDTH = 32
CELL_HEIGHT = 24
ATLAS_COLUMNS = 16

DBIP_NOTICE = """IP Geolocation by DB-IP (https://db-ip.com)

Lookout's country data is DB-IP's IP to Country Lite database, edition {month}, licensed under the Creative Commons
Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). Lookout keeps only its IPv4
ranges, converted to a compact lookup table.
"""

FLAGS_NOTICE = """Flags from flag-icons {tag} (https://github.com/lipis/flag-icons), rendered to bitmaps.

{licence}"""


def read_ranges(month):
	# DB-IP answers 403 to urllib's default User-Agent.
	request = urllib.request.Request(DBIP_URL.format(month=month), headers={ "User-Agent": "lookout-make-geo" })

	with urllib.request.urlopen(request) as response:
		text = gzip.decompress(response.read()).decode()

	ranges = []

	for first, last, code in csv.reader(io.StringIO(text)):
		if ":" not in first:
			ranges.append((int(ipaddress.IPv4Address(first)), int(ipaddress.IPv4Address(last)), code))

	ranges.sort()
	return ranges


def build_table(ranges, index_of):
	starts = []
	indices = []

	def append(start, index):
		if not indices or indices[-1] != index:
			starts.append(start)
			indices.append(index)

	next_start = 0

	for first, last, code in ranges:
		if first < next_start:
			sys.exit(f"overlapping ranges at {ipaddress.IPv4Address(first)}")

		if first > next_start:
			append(next_start, NO_COUNTRY)

		append(first, index_of.get(code, NO_COUNTRY))
		next_start = last + 1

	if next_start <= 0xFFFFFFFF:
		append(next_start, NO_COUNTRY)

	return starts, indices


def build_atlas(codes, flags_dir, work_dir, output):
	cells = []

	for index, code in enumerate(codes):
		cell = work_dir / f"{index:03}.png"
		subprocess.run(["rsvg-convert", "--width", str(CELL_WIDTH), "--height", str(CELL_HEIGHT), "--output", str(cell),
			str(flags_dir / "flags" / "4x3" / f"{code.lower()}.svg")], check=True)
		cells.append(str(cell))

	subprocess.run(["magick", "montage", *cells, "-tile", f"{ATLAS_COLUMNS}x", "-geometry",
		f"{CELL_WIDTH}x{CELL_HEIGHT}+0+0", "-background", "none", "-strip", "-define", "png:exclude-chunks=date,time",
		f"PNG32:{output}"], check=True)


def cpp_string(text):
	return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_country_table(codes, names, month, tag, output):
	rows = "\n".join(f"\tSCountry{{ {cpp_string(code)}, {cpp_string(names[code])} }}," for code in codes).rstrip(",")
	output.write_text(f"""// Generated by tools/make-geo.py from DB-IP {month} and flag-icons {tag}; do not edit.
#include "country_table.hpp"
#include <array>

namespace Lkt::Geo
{{
namespace
{{
constexpr std::array<SCountry, {len(codes)}> Countries
{{
{rows}
}};
}} // namespace

//////////////////////////////////////////////////////////////////////////
std::span<SCountry const> GetCountryTable()
{{
	return Countries;
}}
}} // namespace Lkt::Geo
""")


def main():
	parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument("month", help="DB-IP edition, YYYY-MM")
	parser.add_argument("tag", help="flag-icons release tag, e.g. v7.5.0")
	arguments = parser.parse_args()

	ranges = read_ranges(arguments.month)

	with tempfile.TemporaryDirectory() as temp:
		flags_dir = pathlib.Path(temp) / "flag-icons"
		subprocess.run(["git", "-c", "advice.detachedHead=false", "clone", "--quiet", "--depth", "1", "--branch",
			arguments.tag, FLAGS_REPO, str(flags_dir)], check=True)
		names = {entry["code"].upper(): entry["name"] for entry in json.loads((flags_dir / "country.json").read_text())}
		codes = sorted({code for _, _, code in ranges} - {UNKNOWN_CODE})
		missing = [code for code in codes
			if code not in names or not (flags_dir / "flags" / "4x3" / f"{code.lower()}.svg").is_file()]

		if missing:
			sys.exit(f"no flag or name in flag-icons {arguments.tag} for: {' '.join(missing)}")

		if len(codes) >= NO_COUNTRY:
			sys.exit(f"{len(codes)} countries do not fit a byte beside the no-country value")

		geo_dir = ROOT / "assets" / "geo"
		geo_dir.mkdir(parents=True, exist_ok=True)

		starts, indices = build_table(ranges, {code: index for index, code in enumerate(codes)})
		table = struct.pack(f"<I{len(starts)}I", len(starts), *starts) + bytes(indices)
		(geo_dir / "ipv4-countries.bin").write_bytes(table)

		work_dir = pathlib.Path(temp) / "cells"
		work_dir.mkdir()
		build_atlas(codes, flags_dir, work_dir, geo_dir / "flags.png")

		write_country_table(codes, names, arguments.month, arguments.tag,
			ROOT / "src" / "geo" / "private" / "country_table.cpp")

		licences_dir = ROOT / "assets" / "licences"
		(licences_dir / "dbip-country-lite.txt").write_text(DBIP_NOTICE.format(month=arguments.month))
		(licences_dir / "flag-icons.txt").write_text(FLAGS_NOTICE.format(tag=arguments.tag,
			licence=(flags_dir / "LICENSE").read_text()))

	print(f"{len(codes)} countries, {len(starts)} ranges, table {len(table) / 1048576:.2f} MiB")


if __name__ == "__main__":
	main()
